type: vertical-stack
cards:
  - type: 'custom:mini-media-player'
    hide_when_off: true
    hide:
      volume: false
      source: false
      power_state: false
      controls: true
    icon_state: true
    toggle_power: true
    group: true
    sound_mode: full
    source: icon
    artwork: none
    name: Alexa Quarto
    volume_stateless: false
    replace_mute: play_pause
    entity: media_player.quarto
    info: scroll
  - type: 'custom:button-card'
    styles:
      card:
        - height: 120px
        - border-radius: 3%
        - font: 13px/13px Roboto
    entity: media_player.quarto
    show_entity_picture: true
    show_name: true
    layout: icon_state_name2nd
    show_label: true
    state:
      - operator: template
        value: >
          [[[ return
          states['media_player.quarto'].attributes.media_content_id ===
          'Radio Comercial' && states['media_player.quarto'].state ===
          'playing']]]
        label: >
          [[[ return 'Status: ' + states['media_player.quarto'].state + "
          Radio Comercial"]]]
        color: yellow
        icon: 'mdi:music'
        styles:
          card:
            - animation: blink 2s ease infinite
          label:
            - padding: 5px
          name:
            - margin-top: '-23px'
      - operator: template
        value: >
          [[[ return
          states['media_player.quarto'].attributes.media_content_id ===
          'vodafone.fm' && states['media_player.quarto'].state ===
          'playing']]]
        label: >
          [[[ return 'Status: ' + states['media_player.quarto'].state + "
          Vodafone.fm"]]]
        color: yellow
        icon: 'mdi:music'
        styles:
          card:
            - animation: blink 2s ease infinite
          label:
            - padding: 5px
          name:
            - margin-top: '-30px'
      - operator: template
        value: >
          [[[ return
          states['media_player.quarto'].attributes.media_content_id ===
          'M80-Rádio' && states['media_player.quarto'].state ===
          'playing']]]
        label: >
          [[[ return 'Status: ' + states['media_player.quarto'].state + "
          M80-Rádio"]]]
        color: yellow
        icon: 'mdi:music'
        styles:
          card:
            - animation: blink 2s ease infinite
          label:
            - padding: 5px
          name:
            - margin-top: '-30px'
      - operator: template
        value: >
          [[[ return
          states['media_player.quarto'].attributes.media_content_id ===
          'Portugal RFM' && states['media_player.quarto'].state ===
          'playing']]]
        label: >
          [[[ return 'Status: ' + states['media_player.quarto'].state + "
          Portugal RFM"]]]
        color: yellow
        icon: 'mdi:music'
        styles:
          card:
            - animation: blink 2s ease infinite
          label:
            - padding: 5px
          name:
            - margin-top: '-30px'
      - operator: template
        value: >
          [[[ return
          states['media_player.quarto'].attributes.media_content_id ===
          'cidade FM' && states['media_player.quarto'].state ===
          'playing']]]
        label: >
          [[[ return 'Status: ' + states['media_player.quarto'].state + "
          Cidade FM"]]]
        color: yellow
        icon: 'mdi:music'
        styles:
          card:
            - animation: blink 2s ease infinite
          label:
            - padding: 5px
          name:
            - margin-top: '-30px'
      - operator: template
        value: >
          [[[ return
          states['media_player.quarto'].attributes.media_content_id ===
          'Mega-Hits' && states['media_player.quarto'].state ===
          'playing']]]
        label: >
          [[[ return 'Status: ' + states['media_player.quarto'].state + "
          Mega Hits"]]]
        color: yellow
        icon: 'mdi:music'
        styles:
          card:
            - animation: blink 2s ease infinite
          label:
            - padding: 5px
          name:
            - margin-top: '-30px'
      - operator: template
        value: >
          [[[ return
          states['media_player.quarto'].attributes.media_content_id ===
          'Radio-Nova-Era' && states['media_player.quarto'].state ===
          'playing']]]
        label: >
          [[[ return 'Status: ' + states['media_player.quarto'].state + "
          Radio-Nova-Era"]]]
        color: yellow
        icon: 'mdi:music'
        styles:
          card:
            - animation: blink 2s ease infinite
          label:
            - padding: 5px
          name:
            - margin-top: '-30px'
      - operator: template
        value: |
          [[[ return states['media_player.quarto'].state === 'playing']]]
        label: >
          [[[ return 'Status: ' + states['media_player.quarto'].state + "
          " + states['media_player.quarto'].attributes.media_artist + " -
          " + states['media_player.quarto'].attributes.media_title]]]
        color: yellow
        icon: 'mdi:music'
        styles:
          card:
            - animation: blink 2s ease infinite
          label:
            - padding: 5px
          name:
            - margin-top: '-30px'
      - operator: default
        label: >
          [[[ return  'Status: ' +
          states['media_player.quarto'].state]]]   
  - type: horizontal-stack
    cards:
      - type: 'custom:button-card'
        tap_action:
          action: call-service
          service: script.radio_comercial_quarto
        styles:
          entity_picture:
            - width: 80%
          card:
            - background-color: ivory
            - border-radius: 3%
            - padding: 5%
            - height: 60px
        entity: media_player.quarto
        entity_picture: /local/radio_logo/Logo_Radio_Comercial.jpg
        show_entity_picture: true
        show_name: false
        state:
          - operator: template
            value: >
              [[[ return
              states['media_player.quarto'].attributes.media_content_id
              === 'Radio Comercial' &&
              states['media_player.quarto'].state === 'playing']]]
            styles:
              card:
                - box-shadow: 0px 0px 5px 5px var(--button-card-light-color)
      - type: 'custom:button-card'
        tap_action:
          action: call-service
          service: script.vodafone_quarto
        styles:
          entity_picture:
            - width: 120%
          card:
            - background-color: ivory
            - border-radius: 3%
            - padding: 5%
            - height: 60px
        entity: media_player.quarto
        entity_picture: /local/radio_logo/logo_vodafone_fm.png
        show_entity_picture: true
        show_name: false
        state:
          - operator: template
            value: >
              [[[ return
              states['media_player.quarto'].attributes.media_content_id
               === 'Vodafone.fm' &&
               states['media_player.quarto'].state === 'playing']]]
            styles:
              card:
                - box-shadow: 0px 0px 5px 5px var(--button-card-light-color)
      - type: 'custom:button-card'
        tap_action:
          action: call-service
          service: script.m80_quarto
        styles:
          entity_picture:
            - width: 70%
          card:
            - background-color: ivory
            - border-radius: 3%
            - padding: 5%
            - height: 60px
        entity: media_player.quarto
        entity_picture: /local/radio_logo/logo_m80.png
        show_entity_picture: true
        show_name: false
        state:
          - operator: template
            value: >
              [[[ return
              states['media_player.quarto'].attributes.media_content_id
              === 'M80-Rádio' && states['media_player.quarto'].state ===
              'playing']]]
            styles:
              card:
                - box-shadow: 0px 0px 5px 5px var(--button-card-light-color)
      - type: 'custom:button-card'
        tap_action:
          action: call-service
          service: script.rfm_quarto
        styles:
          entity_picture:
            - width: 70%
          card:
            - background-color: ivory
            - border-radius: 3%
            - padding: 5%
            - height: 60px
        entity: media_player.quarto
        entity_picture: /local/radio_logo/logo_rfm.png
        show_entity_picture: true
        show_name: false
        state:
          - operator: template
            value: >
              [[[ return
              states['media_player.quarto'].attributes.media_content_id
              === 'Portugal RFM' && states['media_player.quarto'].state
              === 'playing']]]
            styles:
              card:
                - box-shadow: 0px 0px 5px 5px var(--button-card-light-color)
  - type: horizontal-stack
    cards:
      - type: 'custom:button-card'
        tap_action:
          action: call-service
          service: script.cidadefm_quarto
        styles:
          entity_picture:
            - width: 130%
          card:
            - background-color: false
            - border-radius: 3%
            - padding: 0%
            - height: 60px
        entity: media_player.quarto
        entity_picture: /local/radio_logo/logo_cidade_fm.png
        show_entity_picture: true
        show_name: false
        state:
          - operator: template
            value: >
              [[[ return
              states['media_player.quarto'].attributes.media_content_id
               === 'cidade FM' &&
               states['media_player.quarto'].state === 'playing']]]
            styles:
              card:
                - box-shadow: 0px 0px 5px 5px var(--button-card-light-color)
      - type: 'custom:button-card'
        tap_action:
          action: call-service
          service: script.tsf_quarto
        styles:
          entity_picture:
            - width: 50%
          card:
            - background-color: ivory
            - border-radius: 3%
            - padding: 5%
            - height: 60px
        entity: media_player.quarto
        entity_picture: /local/radio_logo/logo_tsf.png
        show_entity_picture: true
        show_name: false
        state:
          - operator: template
            value: >
              [[[ return
              states['media_player.quarto'].attributes.media_content_id
               === 'TSF Radio Noticias' &&
               states['media_player.quarto'].state === 'playing']]]
            styles:
              card:
                - box-shadow: 0px 0px 5px 5px var(--button-card-light-color)
      - type: 'custom:button-card'
        tap_action:
          action: call-service
          service: script.megahits_quarto
        styles:
          entity_picture:
            - width: 40%
          card:
            - background-color: ivory
            - border-radius: 3%
            - padding: 5%
            - height: 60px
        entity: media_player.quarto
        entity_picture: /local/radio_logo/logo_megahits.png
        show_entity_picture: true
        show_name: false
        state:
          - operator: template
            value: >
              [[[ return
              states['media_player.quarto'].attributes.media_content_id
               === 'Mega-Hits' &&
               states['media_player.quarto'].state === 'playing']]]
            styles:
              card:
                - box-shadow: 0px 0px 5px 5px var(--button-card-light-color)
      - type: 'custom:button-card'
        tap_action:
          action: call-service
          service: script.novaera_quarto
        styles:
          entity_picture:
            - width: 100%
          card:
            - background-color: ivory
            - border-radius: 3%
            - padding: 5%
            - height: 60px
        entity: media_player.quarto
        entity_picture: /local/radio_logo/logo_nova_era.png
        show_entity_picture: true
        show_name: false
        state:
          - operator: template
            value: >
              [[[ return
              states['media_player.quarto'].attributes.media_content_id
               === 'Radio-Nova-Era' &&
               states['media_player.quarto'].state === 'playing']]]
            styles:
              card:
                - box-shadow: 0px 0px 5px 5px var(--button-card-light-color)
  - type: conditional
    conditions:
      - entity: media_player.quarto
        state: playing
      - entity: sensor.estacoes_radio_quarto
        state: Comercial
    card:
      type: vertical-stack
      cards:
        - type: picture-glance
          image: 'https://demo.home-assistant.io/stub_config/kitchen.png'
          entities: []
          camera_image: camera.comercial
        - type: entities
          entities:
            - entity: sensor.artista
              name: Artista
            - entity: sensor.musica
              name: Música
            - entity: sensor.album
              name: Álbum
            - entity: sensor.titulos
  - type: conditional
    conditions:
      - entity: media_player.quarto
        state: playing
      - entity: sensor.estacoes_radio_quarto
        state: Vodafone
    card:
      type: vertical-stack
      cards:
        - type: picture-glance
          image: 'https://demo.home-assistant.io/stub_config/kitchen.png'
          entities: []
          camera_image: camera.vodafone
        - type: entities
          entities:
            - entity: sensor.artista_vodafone
              name: Artista
            - entity: sensor.musica_vodafone
              name: Música
            - entity: sensor.album_vodafone
              name: Álbum
            - entity: sensor.titulos_vodafone
              name: Títulos
  - type: conditional
    conditions:
      - entity: media_player.quarto
        state: playing
      - entity: sensor.estacoes_radio_quarto
        state: M80
    card:
      type: vertical-stack
      cards:
        - type: picture-glance
          image: 'https://demo.home-assistant.io/stub_config/kitchen.png'
          entities: []
          camera_image: camera.m80
        - type: entities
          entities:
            - entity: sensor.artista_m80
              name: Artista
            - entity: sensor.musica_m80
              name: Música
            - entity: sensor.album_m80
              name: Álbum
            - entity: sensor.titulos_m80
              name: Títulos
  - type: conditional
    conditions:
      - entity: media_player.quarto
        state: playing
      - entity: sensor.estacoes_radio_quarto
        state: RFM
    card:
      type: vertical-stack
      cards:
        - type: picture-glance
          image: 'https://demo.home-assistant.io/stub_config/kitchen.png'
          entities: []
          camera_image: camera.rfm
        - type: entities
          entities:
            - entity: sensor.artista_rfm
              name: Artista
            - entity: sensor.rfm_album
              name: Música
  - type: conditional
    conditions:
      - entity: media_player.quarto
        state: playing
      - entity: sensor.estacoes_radio_quarto
        state: CidadeFM
    card:
      type: vertical-stack
      cards:
        - type: picture-glance
          image: 'https://demo.home-assistant.io/stub_config/kitchen.png'
          entities: []
          camera_image: camera.cidadefm
        - type: entities
          entities:
            - entity: sensor.artista_cidadefm
              name: Artista
            - entity: sensor.musica_cidadefm
              name: Música
            - entity: sensor.album_cidadefm
              name: Álbum
            - entity: sensor.titulos_cidadefm
              name: Títulos
  - type: conditional
    conditions:
      - entity: media_player.quarto
        state: playing
      - entity: sensor.estacoes_radio_quarto
        state: TSFRadioNoticias
    card:
      type: vertical-stack
      cards:
        - type: picture-glance
          image: >-
            https://static.globalnoticias.pt/tsf/image.jpg?brand=TSF&type=generate&guid=b9ee83cc-8a84-437e-a4ce-9167d5863bd1&w=800&h=450&t=20200616054433
          entities: []
  - type: conditional
    conditions:
      - entity: media_player.quarto
        state: playing
      - entity: sensor.estacoes_radio_quarto
        state: MegaHits
    card:
      type: vertical-stack
      cards:
        - type: picture-glance
          image: 'https://demo.home-assistant.io/stub_config/kitchen.png'
          entities: []
          camera_image: camera.megahits
        - type: entities
          entities:
            - entity: sensor.megahits_artist
              name: Artista
            - entity: sensor.megahits_music
              name: Música
            - entity: sensor.megahits_show_name
              name: Títulos
  - type: conditional
    conditions:
      - entity: media_player.quarto
        state: playing
      - entity: sensor.estacoes_radio_quarto
        state: NovaEra
    card:
      type: vertical-stack
      cards:
        - type: picture-glance
          entities: []
          image: >-
            https://www.radionovaera.pt/wp-content/uploads/2016/09/geral-02-1024x378.jpg
        - type: entities
          entities:
            - entity: sensor.nova_era_artist
              name: Artista
            - entity: sensor.nova_era_music
              name: Música